name: Update userscript meta

# give GITHUB_TOKEN contents: write so commits can push
permissions:
  contents: write

on:
  push:
    paths:
      - '*.user.js'

jobs:
  extract_meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract metadata for all userscripts
        run: |
          shopt -s nullglob
          for file in *.user.js; do
            if [[ "$file" != *_meta.user.js ]]; then
              out="${file%.user.js}_meta.user.js"
              echo "Generating $out from $file"
              sed -n '/^\/\/ ==UserScript==$/,/^\/\/ ==\/UserScript==$/p' "$file" > "$out"
            fi
          done

      - name: Commit meta files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update userscript meta'
          file_pattern: '*_meta.user.js'
